themes:
  - name: Light
    applicationBackground: f0f3f9
    textColor: 000000
    operatorBackground: f7f9fc
    numbersBackground: ffffff
    btnEqualTextColor: ffffff
    btnEqualBackground: 0067c0
  - name: Dark
    applicationBackground: 1c2028
    textColor: ffffff
    operatorBackground: 2d333d
    numbersBackground: 363c47
    btnEqualTextColor: ffffff
    btnEqualBackground: 4cc2ff
  - name: Matrix
    applicationBackground: 000000
    textColor: 00ff00
    operatorBackground: 003300
    numbersBackground: 002200
    btnEqualTextColor: 000000
    btnEqualBackground: 00ff00